_default:

    # VCS CONFIG
    vcs: git

    # PREREQUISITES
    #  Actions executed before any questions get asked to the user.
    #  Custom action can be added by provided a relative path the the php script. Example:
    #   - relative/path/to/your-own-sript.php
    prerequisites:
     - working-copy-check
#     - display-last-changes

    # GENERAL CONFIG
    #  Apply to all branches except the one from the 'branch-specific' section
    #  Like prerequisites, you can add your own script. Example:
    #   - relative/path/to/your-own-sript.php
    version-generator: semantic              # Simple versionning
    version-persister: changelog
    pre-release-actions:
      changelog-update:          # Update a CHANGELOG file before the release
        format: semantic
      composer-update:
        name: composer.json

# BRANCH SPECIFIC CONFIG
#  On master, we override the general config
master:
    version-generator: semantic # More complex versionning (semantic)
    version-persister: changelog
    pre-release-actions:
        changelog-update:          # Update a CHANGELOG file before the release
            format: semantic
        composer-update:
            name: composer.json